apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-deploy-dev #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  namespace: apd-ns-dev
  labels:
    app: adp-dev
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: adp-dev
  template:
    metadata:
      labels:
        app: adp-dev
    spec:
      containers:
      - name: adp-dev #The name of the react.js application container
        image: lvtujingji/adp-dev:latest
        ports:
        - containerPort: 80 #The port for the React.js application   container
---
apiVersion: v1
kind: Service
metadata:
  name: adp-svc-dev #The name of the Kubernetes Service to be created in the Kubernetes cluster
  metadata: adp-ns-dev
spec:
  selector:
    app: adp-dev 
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port:  80 #Service port
    targetPort: 80 #The port for the React.js application container
