apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    env: 
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
        #- name: AWS_EC2_METADATA_DISABLED
        #value: "true"
      #- name: AWS_ECR_DISABLE_CACHE
      #value: "true"
    args: 
    - "--verbosity=trace"
    - "--dockerfile=dockerfile"
    - "--context=git://github.com/lvtujingji/lvtujingji.git#refs/heads/main"
    - "--destination=020332153965.dkr.ecr.us-east-2.amazonaws.com/adp-ecr-dev:nginx-v1.14" # replace with your dockerhub account
    volumeMounts:
    - name: ecrconfig
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: ecrconfig
    configMap:
      name: ecrconfig
    #  secret:
    #    secretName: regcred
    #    items: 
    #      - key: .dockerconfigjson
    #        path: config.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ecrconfig
data: 
  config.json: |
    { "credsStore": "ecr-login"}

