apiVersion: apps/v1
kind: Deployment
metadata:
  name: adp-nginx-prod
  namespace: adp-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adp-nginx-prod
  template:
    metadata:
      labels:
        app: adp-nginx-prod
    spec:
      containers:
        - name: nginx
          image: 547384405015.dkr.ecr.us-east-1.amazonaws.com/adp-ecr-dev:nginx-v1.14
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 80
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: adp-nginx-svc-prod
  namespace: adp-prod
spec:
  selector: 
    app: adp-nginx-prod
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adp-nginx-ingress-prod
  namespace: adp-prod
spec:
  rules:
  - host: prod.lvtujingji.click
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adp-nginx-svc-prod
            port:
              number: 80
